server:
  mode: "debug"
  port: "8080"
  work_dir: "/Users/cengdong/GolandProjects/faker-douyin/"
  log_dir: "/Users/cengdong/GolandProjects/faker-douyin/logs/"

log:
  filename: "douyin.log"
  level:
    app: "debug"
    gorm: "info"
  max_size: 10
  max_age: 30
  compress: false

mysql:
  host: "192.168.18.3"
  port: "3306"
  user: "root"
  password: "123456"
  name: "douyin"

redis:
  host: "192.168.18.3"
  port: "6379"
  password: "123456"
  db: 0

rabbitmq:
  host: "192.168.18.3"
  port: "5672"
  user: "guest"
  password: "guest"

ssh:
  host: "192.168.18.3"
  port: "22"
  user: "ftpuser"
  password: "123456"
  type_ssh: "password"

ftp:
  host: "192.168.18.3"
  port: "21"
  user: "ftpuser"
  password: "123456"
  heartbeat_time: 120


