// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID             int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	CreatedAt      time.Time      `gorm:"column:created_at;type:datetime(3);not null" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:datetime(3);not null" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	UserID         int64          `gorm:"column:user_id;type:bigint unsigned;not null" json:"user_id"`
	VideoID        int64          `gorm:"column:video_id;type:bigint unsigned;not null" json:"video_id"`
	CommentContent string         `gorm:"column:comment_content;type:longtext;not null" json:"comment_content"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
