// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameVideo = "videos"

// Video mapped from table <videos>
type Video struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	AuthorID  int64          `gorm:"column:author_id;type:bigint unsigned;not null" json:"author_id"`
	Title     string         `gorm:"column:title;type:longtext;not null" json:"title"`
	PlayURL   string         `gorm:"column:play_url;type:longtext;not null" json:"play_url"`
	CoverURL  string         `gorm:"column:cover_url;type:longtext;not null" json:"cover_url"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
